# This is a basic workflow to help you get started with Actions

name: Zip Lambda & Upload to S3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    name: Zip & Upload Lambda
    steps:
    - uses: actions/checkout@master
      name: Get the repo files

    - run: mkdir -p ./artifacts

    - uses: montudor/action-zip@v1
      name: Zip the contents of the lambda folder
      with:
        args: zip -r ./artifacts/lambda_function_payload.zip lambda

    - uses: actions/upload-artifacts@v2
      name: Upload zip of lambda
      with:
        name: lambda-payload
        path: ./artifacts/lambda_function_payload.zip

  terraform_plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifacts@v2
      with:
        name: lambda-payload
        path: artifacts

    - uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false
        terraform_version: 1.2.2